### ISSUE TITLE
Add full support to T12 - auto mode

### ISSUE THREAD

**Issue by fazioa** [souliss/bindingopenhab#1]

**Comment by fazioa** [comment]
TO DO - Support to auto mode

Command recap, using: 
        -  1(hex) as command, toogle the output 
        -  2(hex) as command, the output move to ON the mode is reset
        -  4(hex) as command, the output move to OFF the mode is reset
        -  8(hex) as command, the mode is set to AUTO
        - >8(hex) as command, time the output to ON if in AUTO 
        -  0(hex) as command, no action

Output status,
        -  0(hex) for output OFF and mode not in AUTO,
        -  1(hex) for output ON and mode not in AUTO,
        - F0(hex) for output OFF and mode in AUTO,
        - F1(hex) for output ON and mode in AUTO.

**Comment by fazioa** [comment]
@plinioseniore @FulvioSpelta Your opinion?
Can we add support or leave to OH auto-mode function?

**Comment by plinioseniore** [comment]
This is useful, because you can set the T12 in manual to avoid that is
triggered automatically.

Should be supported in OH.

Dario.

From Mobile.
