### ISSUE TITLE
Support T14 Pulse Output

### ISSUE THREAD

**Issue by litris** [souliss/bindingopenhab#10]
I would have T14 Pulse Output in Openhab.

Use as T11 vs T14 but not refresh button state on Openhab.

I have a house automated with Automata Siemens S7-200. 

And I have all entries pushbutton. 

I need to turn those entries with T14 Output. 

Thank you.

**Comment by fazioa** [comment]
T14 (Pulse Digital Output) only do a pulse. The output state change to on only for a short time and then back to off.
If you need a pulse output with feedback you have to use T18 ( ON/OFF Digital Output with pulse output)

**Comment by litris** [comment]
Is a pulse but no refresh button state.

http://youtu.be/roTjh-aUlfY

**Comment by fazioa** [comment]
A pulse is a on state for a vey short time, then item back OFF.
Do you have a feedback?
Il 21/dic/2015 00:14, "litris" notifications@github.com ha scritto:

**Comment by litris** [comment]
Is to open a door only you need a second in pulse mode.

 App works correctly in Souliss.

 Openhab But when I click on the "On" button pressing 1s ago but the icon stays on.

 If I want to press the same button the first click the icon off but does not send or have to press to press.

 If there are multiple always it falls down last used as seen in the video.

 What I need is for the "On" icon to remain as pressing on and reset to the OFF or OFF icon.

 As in Souliss App.

 If instead of using an "On" icon use an "on-off" button the same can you stay in the portion of ON until you press another or the same.

 Thank you.

**Comment by marcolino7** [comment]
Hi,
I use a T14 with success using this code on OpenHab:

items:
Switch HVAC_1_SEND  "Invia " (gpHVAC_CamCuc_Send) {souliss="T11:6:9", autoupdate="false"}

sitemap:
Switch item=HVAC_1_SEND mappings=[ON="Invia"]

Give it a try and let me know

**Comment by litris** [comment]
Thanks, I try it and you commented how it goes.

**Comment by litris** [comment]
It is the same that I have put in my Openhab.

I tried it with T11 and T14 with the same result.

items:
Switch Vivienda "Vivienda" <lock> (Puertas, grp1, TechnicView_Node0) {souliss="T14:0:13", autoupdate="false"}

sitemap:
Switch item=Vivienda mappings=[ON="PULSA"]

**Comment by fazioa** [comment]
Ah OK.
It is a problem openhab UI. It sometime don't refresh display immediately.
You can use mapping to display only ON commando to workaround this problem.
Il 21/dic/2015 11:28, "Marco" notifications@github.com ha scritto:

**Comment by litris** [comment]
I do not understand.
If you use only or with ON or without ON-OFF Mappins the result is always the same it remains powered.

Switch item=Vivienda mappings=[ON="On", OFF="Off"]
Switch item=Vivienda mappings=[ON="PULSA"]
Switch item=Vivienda

Same result in the three examples.

**Comment by litris** [comment]
Openhab APP occurs in iOS and Android.

Now I've tried from the Mac Safari browser and works well.

The problem seems to be Openhab UI, as you said.

**Comment by litris** [comment]
Video:
https://youtu.be/afJUJK-lUYE

App Openhab and Explorer.
