### ISSUE TITLE
Add T11 support for timed activation

### ISSUE THREAD

**Issue by fazioa** [souliss/bindingopenhab#2]
> 30(hex) as command, time the output to ON

**Comment by juanpintom** [comment]
And you can send from 31(hex) to FF to set the number of cycles until set to OFF

**Comment by plinioseniore** [comment]
The best option is to use the openHAB facility to have timed turn ON/OFF, this feature is intended mostly to have timed OFF from local switches.

**Comment by fazioa** [comment]
Your advice is to not implement timer function? Is true, with OH rules is simple to set timer for light.

**Comment by plinioseniore** [comment]
Yes isn't the best to get a timer in OH.

Dario.

From Mobile.
