### ISSUE TITLE
Support for T12 Auto mode

### ISSUE THREAD

**Issue by plinioseniore** [souliss/bindingopenhab#8]
Actually there is no support for AUTO/MANUAL mode in T12, I suggest to add it in order to have same functionality as in SoulissApp

**Comment by juanpintom** [comment]
We only need a code similar to T11 but sending the auto command instead the
on command, with this we can add 2 items on Oh, one with t11 to control
on/off and another item with the new T12 to do the auto/off switch.

Regards

**Comment by juanpintom** [comment]
We can change this line with 0x08 to change between Auto / Manual and use a T11 to On/OFF

https://github.com/souliss/bindingopenhab/blob/master/openhab/bundles/binding/org.openhab.binding.souliss/resources/properties/commands_OHtoSOULISS.properties#L20

Regards

**Comment by fazioa** [comment]
Yes , you can , but this change is reflected on all T11 . Okay as a temporary change .

**Comment by juanpintom** [comment]
Sorry I not explained well. I mean you can use the same code as t11 to add
the t12 on the binding, this new typical on binding just send auto/off
command and we can use the t11 code to send an on/off command to a t12 and
others t11 too.

Regards

**Comment by fazioa** [comment]
Ahh... Ok. :)
I would use same syntax as T31, but I will use same code of T11.
I think about it.
Il 26/giu/2015 12:54, "juanpintom" notifications@github.com ha scritto:

> Sorry I not explained well. I mean you can use the same code as t11 to add
> the t12 on the binding, this new typical on binding just send auto/off
> command and we can use the t11 code to send an on/off command to a t12 and
> others t11 too.
> 
> Regards

**Comment by juanpintom** [comment]
In my suggestion we just add 2 items on Openhab related to the same T12 SLOT, one item sends ON/OFF commands (using a T11 syntax on binding) and other sends AUTO/OFF commands with the new (cloned) T12 syntax.

I like to help us on this topic but my java knowledge is very poor :( 

Really thanks for your work @fazioa :)

Regards

**Comment by fazioa** [comment]
Switch SwitchAutoMode   "T12"       (TechnicView_Node3) {souliss="T12:3:0:switch", autoupdate="false"}
Switch SwitchAutoMode_setup     "Auto"      (TechnicView_Node3) {souliss="T12:3:0:automode", autoupdate="false"}
